### ISSUE TITLE
Mismatch error on Generator.py

### ISSUE THREAD

**Issue by anthorax1234** [rikdz/GraphWriter#20]
There seems to be an issue with the generator.py code after training. When trying to load the state dict, it gives a mismatch error on the size of the param/model.

**Comment by rikdz** [comment]
I made changes to the repo today, does this error still happen?

**Comment by anthorax1234** [comment]
To test properly, what should the "-data" flag be set to?

**Comment by rikdz** [comment]
set -data to your test data (i.e. preprocessed.test.tsv) and if you are using a custom dataset, then set the -traindata flag to your training data file

**Comment by anthorax1234** [comment]
Everything is working perfectly now. Thanks a lot for the quick replies!
