### ISSUE TITLE
Question about the reverse() function in lastDataset.py

### ISSUE THREAD

**Issue by vnik18** [rikdz/GraphWriter#5]
Hello, thanks for sharing your code! I have a question about the reverse() function in the file lastDataset.py:

`def reverse(self,x,ents):

    ents = ents[0]

    vocab = self.TGT.vocab

    s = ' '.join([vocab.itos[y] if y<len(vocab.itos) else ents[y-len(vocab.itos)].upper() for j,y in enumerate(x)]) 
  
    if "<eos>" in s: s = s.split("<eos>")[0]

    return s`

What does the line `ents = ents[0]` mean here? It looks like the parameter `ents` gets the value of the raw entity list associated with the input instance. Why is only the first entity of the list (`ents[0]`) used? Why not the other entities? Thanks!

**Comment by rikdz** [comment]
rawents is all of the entities across the batch, a list of lists. For testing, batch size is 1, so rawents is a list with 1 element, which is a list of entities for the testing instance.
